[package]
name = "auto_impl_async_await_example"
version = "0.0.0"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
auto_impl = { path = "../../" }
async-trait = "0.1"
async-std = { version = "1", features = ["attributes"] }
