name: CI

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  check:
    name: 'Build & test'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust-version: ['stable', 'beta', 'nightly', '1.37']
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust-version }}
        default: true
    - uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo build
    - name: Run tests
      if: matrix.rust-version != '1.37'
      run: cargo test --all -- --skip ui_compile_fail
    - name: Run compile-fail tests
      if: matrix.rust-version == 'stable'
      run: cargo test -- ui_compile_fail
    - name: Run tests (MSRV)
      if: matrix.rust-version == '1.37'
      run: cargo test -- --skip ui_compile_fail
